# Generated by Django 4.0.6 on 2022-08-04 17:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'PATIENT'), (2, 'NURSE')], default=1, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('nurse_name', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='Images/Nurses')),
                ('service_name', models.CharField(max_length=100)),
                ('service_price', models.CharField(max_length=100)),
                ('service_area', models.CharField(max_length=100)),
                ('booking_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service Area',
            },
        ),
        migrations.CreateModel(
            name='BookedAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('nurse_name', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='Images/Nurses')),
                ('service_name', models.CharField(max_length=100)),
                ('service_price', models.CharField(max_length=100)),
                ('service_area', models.CharField(max_length=100)),
                ('booking_time', models.CharField(max_length=100)),
                ('total', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Booked Appointment',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='Images/Diagnostic')),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Sock', 'Out Stock')], max_length=100, null=True)),
                ('status_tag', models.CharField(choices=[('in-stock', 'in-stock'), ('out-of-stock', 'out-of-stock')], max_length=100, null=True)),
                ('cart_tag', models.CharField(choices=[('none', 'none'), ('disabled', 'disabled')], default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic',
            },
        ),
        migrations.CreateModel(
            name='DoctorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Doctor Experience',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Doctor Speciality',
            },
        ),
        migrations.CreateModel(
            name='HealthPackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Health Package Price Range',
            },
        ),
        migrations.CreateModel(
            name='HealthPackageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default=None, upload_to='Images/HealthPackage')),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('price_range', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.healthpackageprice')),
            ],
            options={
                'verbose_name_plural': 'Health Package Product',
            },
        ),
        migrations.CreateModel(
            name='MedcartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Medcart Category',
            },
        ),
        migrations.CreateModel(
            name='MedcartPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Medcart Price',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='Images/Nurse')),
                ('price', models.CharField(max_length=100)),
                ('introduction', models.CharField(default=None, max_length=300)),
                ('p_developement', models.CharField(default=None, max_length=100)),
                ('education', models.CharField(default=None, max_length=200)),
                ('language', models.CharField(default=None, max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
            ],
            options={
                'verbose_name_plural': 'Nurse',
            },
        ),
        migrations.CreateModel(
            name='NurseExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nurse Experience',
            },
        ),
        migrations.CreateModel(
            name='NurseSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nurse Speciality',
            },
        ),
        migrations.CreateModel(
            name='OnDemandServicesPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'On Demand Services Price',
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Price Range',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='Images/Product')),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out Sock', 'Out Stock')], max_length=100, null=True)),
                ('status_tag', models.CharField(choices=[('in-stock', 'in-stock'), ('out-of-stock', 'out-of-stock')], max_length=100, null=True)),
                ('cart_tag', models.CharField(choices=[('none', 'none'), ('disabled', 'disabled')], max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('price_range', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pricerange')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Service Name',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='TrustedPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='Images/TrustedPartner')),
            ],
            options={
                'verbose_name_plural': 'Trusted Partner',
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Working Time',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.services'),
        ),
        migrations.CreateModel(
            name='OnDemandServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='Images/DemandServices')),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('price_range', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.ondemandservicesprice')),
            ],
            options={
                'verbose_name_plural': 'On Demand Services',
            },
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='Images/Nurses')),
                ('price', models.CharField(max_length=100)),
                ('introduction', models.CharField(default=None, max_length=300)),
                ('height', models.CharField(default=None, max_length=100)),
                ('weight', models.CharField(default=None, max_length=100)),
                ('p_developement', models.CharField(default=None, max_length=100)),
                ('education', models.CharField(default=None, max_length=200)),
                ('language', models.CharField(default=None, max_length=200)),
                ('experience', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='app.nurseexperience')),
                ('speciality', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='app.nursespeciality')),
            ],
            options={
                'verbose_name_plural': 'Nurses',
            },
        ),
        migrations.CreateModel(
            name='NurseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=150)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nurses Reviews',
            },
        ),
        migrations.CreateModel(
            name='NurseHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('working_time', models.CharField(max_length=100)),
                ('service_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('service_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.servicename')),
            ],
            options={
                'verbose_name_plural': 'Nurse Hire',
            },
        ),
        migrations.AddField(
            model_name='nurse',
            name='experience',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='app.nurseexperience'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='service_area',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.area'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='speciality',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='app.nursespeciality'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='working_time',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.workingtime'),
        ),
        migrations.CreateModel(
            name='Medcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='Images/Medcart')),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.medcartcategory')),
                ('price_range', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.medcartprice')),
            ],
            options={
                'verbose_name_plural': 'Medcart',
            },
        ),
        migrations.CreateModel(
            name='HealthPackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=150)),
                ('healthpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.healthpackageproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Health Package Reviews',
            },
        ),
        migrations.CreateModel(
            name='HealthpackageAvgReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_review', models.CharField(max_length=100, null=True)),
                ('healthpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.healthpackageproduct')),
            ],
            options={
                'verbose_name_plural': 'Health Package Avg Review',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='Images/Doctors')),
                ('position', models.CharField(default=None, max_length=100)),
                ('clinic_price', models.CharField(default=None, max_length=100)),
                ('online_price', models.CharField(default=None, max_length=100)),
                ('statement', models.CharField(default=None, max_length=600)),
                ('bmdc_number', models.CharField(default=None, max_length=100)),
                ('education', models.CharField(default=None, max_length=600)),
                ('experience', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='app.doctorexperience')),
                ('specialities', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='app.doctorspeciality')),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=150)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctors Reviews',
            },
        ),
        migrations.CreateModel(
            name='DemandServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=150)),
                ('demandservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ondemandservices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Demand Service Reviews',
            },
        ),
    ]
