# Generated by Django 4.0.6 on 2022-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
