# Generated by Django 4.0.6 on 2022-08-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nurse_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='price',
        ),
    ]
